/** Amazing Carousel - Responsive jQuery Carousel and Image Scroller
 * Copyright 2013 Magic Hills Pty Ltd All Rights Reserved
 * Website: http://amazingcarousel.com
 * Version 1.6 
 */
(function($){$.fn.html5lightbox=function(options){var inst=this;inst.options=jQuery.extend({autoplay:true,html5player:true,closepos:"bottom",titlepos:"inside",overlaybgcolor:"#000000",overlayopacity:0.9,bgcolor:"#ffffff",bordersize:8,barheight:36,loadingwidth:64,loadingheight:64,resizespeed:400,fadespeed:400,jsfolder:"",skinsfoldername:"skins",loadingimage:"lightbox-loading.gif",nextimage:"lightbox-next.png",previmage:"lightbox-prev.png",closeimage:"../img/lightbox-close.png",playvideoimage:"lightbox-playvideo.png",
titlebgimage:"lightbox-titlebg.png",titlecss:"{color:#333; font-size:16px; font-family:Armata,sans-serif,Arial; overflow:hidden; }",errorwidth:280,errorheight:48,errorcss:"{text-align:center; color:#ff0000; font-size:14px; font-family:Arial, sans-serif;}",supportesckey:true,supportarrowkeys:true,version:"2.3",stamp:false,freemark:"html5box.com",freelink:"http://html5box.com/",watermark:"",watermarklink:""},options);if(typeof html5lightbox_options!="undefined"&&html5lightbox_options)jQuery.extend(inst.options,
html5lightbox_options);inst.options.htmlfolder=window.location.href.substr(0,window.location.href.lastIndexOf("/")+1);inst.options.skinsfolder=inst.options.skinsfoldername;if(inst.options.skinsfolder.length>0&&inst.options.skinsfolder[inst.options.skinsfolder.length-1]!="/")inst.options.skinsfolder+="/";if(inst.options.skinsfolder.charAt(0)!="/"&&inst.options.skinsfolder.substring(0,5)!="http:"&&inst.options.skinsfolder.substring(0,6)!="https:")inst.options.skinsfolder=inst.options.jsfolder+inst.options.skinsfolder;
inst.options.types=["IMAGE","FLASH","VIDEO","YOUTUBE","VIMEO","PDF","MP3","WEB","FLV"];inst.elemArray=new Array;inst.options.curElem=-1;inst.options.flashInstalled=false;try{if(new ActiveXObject("ShockwaveFlash.ShockwaveFlash"))inst.options.flashInstalled=true}catch(e){if(navigator.mimeTypes["application/x-shockwave-flash"])inst.options.flashInstalled=true}inst.options.html5VideoSupported=!!document.createElement("video").canPlayType;inst.options.isChrome=navigator.userAgent.match(/Chrome/i)!=null;
inst.options.isFirefox=navigator.userAgent.match(/Firefox/i)!=null;inst.options.isOpera=navigator.userAgent.match(/Opera/i)!=null||navigator.userAgent.match(/OPR\//i)!=null;inst.options.isSafari=navigator.userAgent.match(/Safari/i)!=null;inst.options.isIE=navigator.userAgent.match(/MSIE/i)!=null&&!inst.options.isOpera;inst.options.isIE9=navigator.userAgent.match(/MSIE 9/i)!=null&&!inst.options.isOpera;inst.options.isIE8=navigator.userAgent.match(/MSIE 8/i)!=null&&!inst.options.isOpera;inst.options.isIE7=
navigator.userAgent.match(/MSIE 7/i)!=null&&!inst.options.isOpera;inst.options.isIE6=navigator.userAgent.match(/MSIE 6/i)!=null&&!inst.options.isOpera;inst.options.isIE678=inst.options.isIE6||inst.options.isIE7||inst.options.isIE8;inst.options.isIE6789=inst.options.isIE6||inst.options.isIE7||inst.options.isIE8||inst.options.isIE9;inst.options.isAndroid=navigator.userAgent.match(/Android/i)!=null;inst.options.isIPad=navigator.userAgent.match(/iPad/i)!=null;inst.options.isIPhone=navigator.userAgent.match(/iPod/i)!=
null||navigator.userAgent.match(/iPhone/i)!=null;inst.options.isMobile=inst.options.isAndroid||inst.options.isIPad||inst.options.isIPhone;inst.options.isIOSLess5=inst.options.isIPad&&inst.options.isIPhone&&(navigator.userAgent.match(/OS 4/i)!=null||navigator.userAgent.match(/OS 3/i)!=null);inst.options.supportCSSPositionFixed=!inst.options.isIE6&&!inst.options.isIOSLess5;inst.options.resizeTimeout=-1;var inst=this;inst.init=function(){inst.showing=false;inst.readData();inst.createMarkup();inst.supportKeyboard()};
var ELEM_TYPE=0,ELEM_HREF=1,ELEM_TITLE=2,ELEM_GROUP=3,ELEM_WIDTH=4,ELEM_HEIGHT=5,ELEM_HREF_WEBM=6,ELEM_HREF_OGG=7;inst.readData=function(){inst.each(function(){if(this.nodeName.toLowerCase()!="a"&&this.nodeName.toLowerCase()!="area")return;var $this=$(this);var fileType=inst.checkType($this.attr("href"));if(fileType<0)return;for(var i=0;i<inst.elemArray.length;i++)if($this.attr("href")==inst.elemArray[i][ELEM_HREF])return;inst.elemArray.push(new Array(fileType,$this.attr("href"),$this.attr("title"),
$this.data("group"),$this.data("width"),$this.data("height"),$this.data("webm"),$this.data("ogg")))})};inst.createMarkup=function(){var fontRef=("https:"==document.location.protocol?"https":"http")+"://fonts.googleapis.com/css?family=Armata";var fontLink=document.createElement("link");fontLink.setAttribute("rel","stylesheet");fontLink.setAttribute("type","text/css");fontLink.setAttribute("href",fontRef);document.getElementsByTagName("head")[0].appendChild(fontLink);var styleCss="#html5-text "+inst.options.titlecss;
styleCss+=".html5-error "+inst.options.errorcss;$("head").append("<style type='text/css'>"+styleCss+"</style>");inst.$lightbox=jQuery("<div id='html5-lightbox' style='display:none;top:0px;left:0px;width:100%;height:100%;z-index:9999999;'>"+"<div id='html5-lightbox-overlay' style='display:block;position:absolute;top:0px;left:0px;width:100%;height:100%;background-color:"+inst.options.overlaybgcolor+";opacity:"+inst.options.overlayopacity+";filter:alpha(opacity="+Math.round(inst.options.overlayopacity*
100)+");'></div>"+"<div id='html5-lightbox-box' style='display:block;position:relative;margin:0px auto;'>"+"<div id='html5-elem-box' style='display:block;position:relative;margin:0px auto;text-align:center;'>"+"<div id='html5-elem-wrap' style='display:block;position:relative;margin:0px auto;text-align:center;background-color:"+inst.options.bgcolor+";'>"+"<div id='html5-loading' style='display:none;position:absolute;top:0px;left:0px;text-align:center;width:100%;height:100%;background:url(\""+inst.options.skinsfolder+
inst.options.loadingimage+"\") no-repeat center center;'></div>"+"<div id='html5-error' class='html5-error' style='display:none;position:absolute;padding:"+inst.options.bordersize+"px;text-align:center;width:"+inst.options.errorwidth+"px;height:"+inst.options.errorheight+"px;'>"+"The requested content cannot be loaded.<br />Please try again later."+"</div>"+"<div id='html5-image' style='display:none;position:absolute;top:0px;left:0px;padding:"+inst.options.bordersize+"px;text-align:center;'></div>"+
"<div id='html5-next' style='display:none;cursor:pointer;position:absolute;right:"+inst.options.bordersize+"px;top:40%;'><img src='"+inst.options.skinsfolder+inst.options.nextimage+"'></div>"+"<div id='html5-prev' style='display:none;cursor:pointer;position:absolute;left:"+inst.options.bordersize+"px;top:40%;'><img src='"+inst.options.skinsfolder+inst.options.previmage+"'></div>"+"</div>"+"</div>"+"<div id='html5-watermark' style='display:none;position:absolute;left:"+String(inst.options.bordersize+
2)+"px;top:"+String(inst.options.bordersize+2)+"px;'></div>"+"</div>"+"</div>");inst.$lightbox.css({position:inst.options.supportCSSPositionFixed?"fixed":"absolute"});inst.$lightbox.appendTo("body");inst.$lightboxBox=$("#html5-lightbox-box",inst.$lightbox);inst.$elem=$("#html5-elem-box",inst.$lightbox);inst.$elemWrap=$("#html5-elem-wrap",inst.$lightbox);inst.$loading=$("#html5-loading",inst.$lightbox);inst.$error=$("#html5-error",inst.$lightbox);inst.$image=$("#html5-image",inst.$lightbox);inst.$next=
$("#html5-next",inst.$lightbox);inst.$prev=$("#html5-prev",inst.$lightbox);var elemText="<div id='html5-elem-data-box' style='display:none;'><div id='html5-text' style='display:block;overflow:hidden;'></div></div>";if(inst.options.titlepos=="over")inst.$elemWrap.append(elemText);else inst.$lightboxBox.append(elemText);inst.$elemData=$("#html5-elem-data-box",inst.$lightbox);inst.$text=$("#html5-text",inst.$lightbox);if(inst.options.titlepos=="over"){inst.$elemData.css({position:"absolute",padding:inst.options.bordersize+
"px",bottom:0,left:0});inst.$text.css({padding:inst.options.bordersize+"px","background-image":"url('"+inst.options.skinsfolder+inst.options.titlebgimage+"')"})}else{inst.$elemData.css({position:"relative",width:"100%",margin:"0px auto",height:inst.options.barheight+"px","background-color":inst.options.bgcolor});inst.$text.css({"float":"left","margin-left":inst.options.bordersize+"px"})}if(inst.options.closepos=="topright")inst.$elemWrap.append("<div id='html5-close' style='display:none;cursor:pointer;position:absolute;top:0;right:0;margin-top:-16px;margin-right:-16px;'><img src='"+
inst.options.skinsfolder+inst.options.closeimage+"'></div>");else inst.$elemData.append("<div id='html5-close' style='display:block;cursor:pointer;float:right;margin-right:"+inst.options.bordersize+"px;'><img src='"+inst.options.skinsfolder+inst.options.closeimage+"'></div>");inst.$close=$("#html5-close",inst.$lightbox);inst.$watermark=$("#html5-watermark",inst.$lightbox);if(inst.options.stamp)inst.$watermark.html("<a href='"+inst.options.freelink+"' style='text-decoration:none;'><div style='display:block;width:120px;height:20px;text-align:center;border-radius:5px;-moz-border-radius:5px;-webkit-border-radius:5px;filter:alpha(opacity=60);opacity:0.6;background-color:#333333;color:#ffffff;font:12px Armata,sans-serif,Arial;'><div style='line-height:20px;'>"+
inst.options.freemark+"</div></div></a>");else if(inst.options.watermark){var html="<img src='"+inst.options.watermark+"' style='border:none;' />";if(inst.options.watermarklink)html="<a href='"+inst.options.watermarklink+"' target='_blank'>"+html+"</a>";inst.$watermark.html(html)}$("#html5-lightbox-overlay",inst.$lightbox).click(inst.finish);inst.$close.click(inst.finish);inst.$next.click(function(){inst.gotoSlide(-1)});inst.$prev.click(function(){inst.gotoSlide(-2)});$(window).resize(function(){if(!inst.options.isMobile){clearTimeout(inst.options.resizeTimeout);
inst.options.resizeTimeout=setTimeout(function(){inst.resizeWindow()},500)}});$(window).scroll(function(){inst.scrollBox()});$(window).bind("orientationchange",function(e){if(inst.options.isMobile)inst.resizeWindow()});inst.enableSwipe()};inst.calcNextPrevElem=function(){inst.options.nextElem=-1;inst.options.prevElem=-1;var j,curGroup=inst.elemArray[inst.options.curElem][ELEM_GROUP];if(curGroup!=undefined&&curGroup!=null){for(j=inst.options.curElem+1;j<inst.elemArray.length;j++)if(inst.elemArray[j][ELEM_GROUP]==
curGroup){inst.options.nextElem=j;break}if(inst.options.nextElem<0)for(j=0;j<inst.options.curElem;j++)if(inst.elemArray[j][ELEM_GROUP]==curGroup){inst.options.nextElem=j;break}if(inst.options.nextElem>=0){for(j=inst.options.curElem-1;j>=0;j--)if(inst.elemArray[j][ELEM_GROUP]==curGroup){inst.options.prevElem=j;break}if(inst.options.prevElem<0)for(j=inst.elemArray.length-1;j>inst.options.curElem;j--)if(inst.elemArray[j][ELEM_GROUP]==curGroup){inst.options.prevElem=j;break}}}};inst.clickHandler=function(){if(inst.elemArray.length<=
0)return true;var $this=$(this);inst.hideObjects();for(var i=0;i<inst.elemArray.length;i++)if(inst.elemArray[i][ELEM_HREF]==$this.attr("href"))break;if(i==inst.elemArray.length)return true;inst.options.curElem=i;inst.options.nextElem=-1;inst.options.prevElem=-1;inst.calcNextPrevElem();inst.$next.hide();inst.$prev.hide();inst.reset();inst.$lightbox.show();if(!inst.options.supportCSSPositionFixed)inst.$lightbox.css("top",$(window).scrollTop());var boxW=inst.options.loadingwidth+2*inst.options.bordersize;
var boxH=inst.options.loadingheight+2*inst.options.bordersize;var winH=window.innerHeight?window.innerHeight:$(window).height();var boxT=Math.round(winH/2-boxH/2);if(inst.options.titlepos!="over")boxT-=Math.round(inst.options.barheight/2);inst.$lightboxBox.css({"margin-top":boxT,"width":boxW,"height":boxH});inst.$elemWrap.css({"width":boxW,"height":boxH});inst.loadCurElem();return false};inst.loadElem=function(elem){inst.showing=true;inst.$elem.unbind("mouseenter").unbind("mouseleave").unbind("mousemove");
inst.$loading.show();switch(elem[ELEM_TYPE]){case 0:var imgLoader=new Image;$(imgLoader).load(function(){inst.showImage(elem,imgLoader.width,imgLoader.height)});$(imgLoader).error(function(){inst.showError()});imgLoader.src=elem[ELEM_HREF];break;case 1:inst.showSWF(elem);break;case 2:case 8:inst.showVideo(elem);break;case 3:case 4:inst.showYoutubeVimeo(elem);break;case 5:inst.showPDF(elem);break;case 6:inst.showMP3(elem);break;case 7:inst.showWeb(elem);break}};inst.loadCurElem=function(){inst.loadElem(inst.elemArray[inst.options.curElem])};
inst.showError=function(){inst.$loading.hide();inst.resizeLightbox(inst.options.errorwidth,inst.options.errorheight,true,function(){inst.$error.show();inst.$elem.fadeIn(inst.options.fadespeed,function(){inst.showData()})})};inst.calcTextWidth=function(objW){return objW-36};inst.showTitle=function(w,t){if(inst.options.titlepos=="inside"){inst.$elemData.css({width:"100%"});inst.$text.css({width:inst.calcTextWidth(w)})}else inst.$elemData.css({width:w});inst.$text.html(t)},inst.showImage=function(elem,
imgW,imgH){var elemW,elemH;if(elem[ELEM_WIDTH])elemW=elem[ELEM_WIDTH];else{elemW=imgW;elem[ELEM_WIDTH]=imgW}if(elem[ELEM_HEIGHT])elemH=elem[ELEM_HEIGHT];else{elemH=imgH;elem[ELEM_HEIGHT]=imgH}var sizeObj=inst.calcElemSize({w:elemW,h:elemH});inst.resizeLightbox(sizeObj.w,sizeObj.h,true,function(){inst.showTitle(sizeObj.w,elem[ELEM_TITLE]);inst.$image.show().css({width:sizeObj.w,height:sizeObj.h});inst.$image.html("<img src='"+elem[ELEM_HREF]+"' width='"+sizeObj.w+"' height='"+sizeObj.h+"' />");inst.$elem.fadeIn(inst.options.fadespeed,
function(){inst.showData()})})};inst.showSWF=function(elem){var dataW=elem[ELEM_WIDTH]?elem[ELEM_WIDTH]:480;var dataH=elem[ELEM_HEIGHT]?elem[ELEM_HEIGHT]:270;var sizeObj=inst.calcElemSize({w:dataW,h:dataH});dataW=sizeObj.w;dataH=sizeObj.h;inst.resizeLightbox(dataW,dataH,true,function(){inst.showTitle(sizeObj.w,elem[ELEM_TITLE]);inst.$image.html("<div id='html5lightbox-swf' style='display:block;width:"+dataW+"px;height:"+dataH+"px;'></div>").show();inst.embedFlash($("#html5lightbox-swf"),dataW,dataH,
elem[ELEM_HREF],"window",{width:dataW,height:dataH});inst.$elem.show();inst.showData()})};inst.showVideo=function(elem){var dataW=elem[ELEM_WIDTH]?elem[ELEM_WIDTH]:480;var dataH=elem[ELEM_HEIGHT]?elem[ELEM_HEIGHT]:270;var sizeObj=inst.calcElemSize({w:dataW,h:dataH});dataW=sizeObj.w;dataH=sizeObj.h;inst.resizeLightbox(dataW,dataH,true,function(){inst.showTitle(sizeObj.w,elem[ELEM_TITLE]);inst.$image.html("<div id='html5lightbox-video' style='display:block;width:"+dataW+"px;height:"+dataH+"px;'></div>").show();
var isHTML5=false;if(inst.options.isIE6789||elem[ELEM_TYPE]==8)isHTML5=false;else if(inst.options.isMobile)isHTML5=true;else if((inst.options.html5player||!inst.options.flashInstalled)&&inst.options.html5VideoSupported)if(!inst.options.isFirefox&&!inst.options.isOpera||(inst.options.isFirefox||inst.options.isOpera)&&(elem[ELEM_HREF_OGG]||elem[ELEM_HREF_WEBM]))isHTML5=true;if(isHTML5){var videoSrc=elem[ELEM_HREF];if(inst.options.isFirefox||inst.options.isOpera||!videoSrc)videoSrc=elem[ELEM_HREF_WEBM]?
elem[ELEM_HREF_WEBM]:elem[ELEM_HREF_OGG];inst.embedHTML5Video($("#html5lightbox-video"),dataW,dataH,videoSrc,inst.options.autoplay)}else{var videoFile=elem[ELEM_HREF];if(videoFile.charAt(0)!="/"&&videoFile.substring(0,5)!="http:"&&videoFile.substring(0,6)!="https:")videoFile=inst.options.htmlfolder+videoFile;inst.embedFlash($("#html5lightbox-video"),dataW,dataH,inst.options.jsfolder+"html5boxplayer.swf","transparent",{width:dataW,height:dataH,videofile:videoFile,hdfile:"",ishd:"0",autoplay:inst.options.autoplay?
"1":"0",errorcss:".html5box-error"+inst.options.errorcss,id:0})}inst.$elem.show();inst.showData()})};inst.prepareYoutubeHref=function(href){var youtubeId="";var regExp=/^.*((youtu.be\/)|(v\/)|(\/u\/\w\/)|(embed\/)|(watch\??v?=?))([^#\&\?]*).*/;var match=href.match(regExp);if(match&&match[7]&&match[7].length==11)youtubeId=match[7];return"http://www.youtube.com/embed/"+youtubeId};inst.showYoutubeVimeo=function(elem){var dataW=elem[ELEM_WIDTH]?elem[ELEM_WIDTH]:480;var dataH=elem[ELEM_HEIGHT]?elem[ELEM_HEIGHT]:
270;var sizeObj=inst.calcElemSize({w:dataW,h:dataH});dataW=sizeObj.w;dataH=sizeObj.h;inst.resizeLightbox(dataW,dataH,true,function(){inst.showTitle(sizeObj.w,elem[ELEM_TITLE]);inst.$image.html("<div id='html5lightbox-video' style='display:block;width:"+dataW+"px;height:"+dataH+"px;'></div>").show();var href=elem[ELEM_HREF];if(elem[ELEM_TYPE]==3)href=inst.prepareYoutubeHref(href);if(inst.options.autoplay)if(href.indexOf("?")<0)href+="?autoplay=1";else href+="&autoplay=1";if(elem[ELEM_TYPE]==3)if(href.indexOf("?")<
0)href+="?wmode=transparent&rel=0";else href+="&wmode=transparent&rel=0";$("#html5lightbox-video").html("<iframe width='"+dataW+"' height='"+dataH+"' src='"+href+"' frameborder='0' webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>");inst.$elem.show();inst.showData()})};inst.showPDF=function(elem){};inst.showMP3=function(elem){};inst.showWeb=function(elem){var winH=window.innerHeight?window.innerHeight:$(window).height();var dataW=elem[ELEM_WIDTH]?elem[ELEM_WIDTH]:$(window).width();
var dataH=elem[ELEM_HEIGHT]?elem[ELEM_HEIGHT]:winH;var sizeObj=inst.calcElemSize({w:dataW,h:dataH});dataW=sizeObj.w;dataH=sizeObj.h;inst.resizeLightbox(dataW,dataH,true,function(){inst.showTitle(sizeObj.w,elem[ELEM_TITLE]);inst.$image.html("<div id='html5lightbox-web' style='display:block;width:"+dataW+"px;height:"+dataH+"px;'></div>").show();$("#html5lightbox-web").html("<iframe width='"+dataW+"' height='"+dataH+"' src='"+elem[ELEM_HREF]+"' frameborder='0'></iframe>");inst.$elem.show();inst.showData()})};
inst.scrollBox=function(){if(!inst.options.supportCSSPositionFixed)inst.$lightbox.css("top",$(window).scrollTop())};inst.resizeWindow=function(){var winH=window.innerHeight?window.innerHeight:$(window).height();var boxT=Math.round(winH/2-inst.$lightboxBox.height()/2);if(inst.options.titlepos!="over")boxT-=Math.round(inst.options.barheight/2);inst.$lightboxBox.animate({"margin-top":boxT},inst.options.resizespeed)};inst.calcElemSize=function(sizeObj){var winH=window.innerHeight?window.innerHeight:$(window).height();
var h0=winH-2*inst.options.bordersize-($(window).width()>600?36:0);if(inst.options.titlepos!="over")h0-=inst.options.barheight;if(sizeObj.h>h0){sizeObj.w=Math.round(sizeObj.w*h0/sizeObj.h);sizeObj.h=h0}var w0=$(window).width()-2*inst.options.bordersize;if(sizeObj.w>w0){sizeObj.h=Math.round(sizeObj.h*w0/sizeObj.w);sizeObj.w=w0}return sizeObj};inst.showData=function(){if(inst.$text.text().length>0||inst.options.closepos=="bottom")inst.$elemData.show();if(inst.options.closepos=="bottom"||inst.$text.text().length>
0&&inst.options.titlepos!="over")inst.$lightboxBox.css({height:String(inst.$lightboxBox.height()+inst.options.barheight)+"px"})};inst.resizeLightbox=function(elemW,elemH,bAnimate,onFinish){var winH=window.innerHeight?window.innerHeight:$(window).height();var speed=bAnimate?inst.options.resizespeed:0;var boxW=elemW+2*inst.options.bordersize;var boxH=elemH+2*inst.options.bordersize;var boxT=Math.round(winH/2-boxH/2);if(inst.options.titlepos!="over")boxT-=Math.round(inst.options.barheight/2);if(boxW==
inst.$elemWrap.width()&&boxH==inst.$elemWrap.height())speed=0;inst.$loading.hide();inst.$watermark.hide();inst.$elem.bind("mouseenter mousemove",function(){if(inst.options.prevElem>=0||inst.options.nextElem>=0){inst.$next.fadeIn();inst.$prev.fadeIn()}});inst.$elem.bind("mouseleave",function(){inst.$next.fadeOut();inst.$prev.fadeOut()});inst.$lightboxBox.css({"margin-top":boxT});inst.$lightboxBox.css({"width":boxW,"height":boxH});inst.$elemWrap.animate({width:boxW},speed).animate({height:boxH},speed,
function(){inst.$loading.show();inst.$watermark.show();inst.$close.show();onFinish()})};inst.reset=function(){if(inst.options.stamp)inst.$watermark.hide();inst.showing=false;inst.$image.empty();inst.$text.empty();inst.$error.hide();inst.$loading.hide();inst.$image.hide();inst.$elemData.hide();inst.$close.hide()};inst.finish=function(){inst.reset();inst.$lightbox.hide();inst.showObjects()};inst.pauseSlide=function(){};inst.playSlide=function(){};inst.gotoSlide=function(slide){if(slide==-1){if(inst.options.nextElem<
0)return;inst.options.curElem=inst.options.nextElem}else if(slide==-2){if(inst.options.prevElem<0)return;inst.options.curElem=inst.options.prevElem}inst.calcNextPrevElem();inst.reset();inst.loadCurElem()};inst.supportKeyboard=function(){$(document).keyup(function(e){if(!inst.showing)return;if(inst.options.supportesckey&&e.keyCode==27)inst.finish();else if(inst.options.supportarrowkeys)if(e.keyCode==39)inst.gotoSlide(-1);else if(e.keyCode==37)inst.gotoSlide(-2)})};inst.enableSwipe=function(){inst.$elem.touchSwipe({preventWebBrowser:true,
swipeLeft:function(){inst.gotoSlide(-1)},swipeRight:function(){inst.gotoSlide(-2)}})};inst.hideObjects=function(){$("select, embed, object").css({"visibility":"hidden"})};inst.showObjects=function(){$("select, embed, object").css({"visibility":"visible"})};inst.embedHTML5Video=function($container,w,h,src,autoplay){$container.html("<div style='position:absolute;display:block;width:"+w+"px;height:"+h+"px;'><video width="+w+" height="+h+(autoplay?" autoplay":"")+" controls='controls' src='"+src+"'></div>");
if(inst.options.isAndroid){var $play=$("<div style='position:absolute;display:block;cursor:pointer;width:"+w+"px;height:"+h+'px;background:url("'+inst.options.skinsfolder+inst.options.playvideoimage+"\") no-repeat center center;'></div>").appendTo($container);$play.unbind("click").click(function(){$("video",$(this).parent())[0].play()})}};inst.embedFlash=function($container,w,h,src,wmode,flashVars){if(inst.options.flashInstalled){var htmlOptions={pluginspage:"http://www.adobe.com/go/getflashplayer",
quality:"high",allowFullScreen:"true",allowScriptAccess:"always",type:"application/x-shockwave-flash"};htmlOptions.width=w;htmlOptions.height=h;htmlOptions.src=src;htmlOptions.flashVars=$.param(flashVars);htmlOptions.wmode=wmode;var htmlString="";for(var key in htmlOptions)htmlString+=key+"="+htmlOptions[key]+" ";$container.html("<embed "+htmlString+"/>")}else $container.html("<div class='html5lightbox-flash-error' style='display:block; position:relative;text-align:center; width:"+w+"px; left:0px; top:"+
Math.round(h/2-10)+"px;'><div class='html5-error'><div>The required Adobe Flash Player plugin is not installed</div><br /><div style='display:block;position:relative;text-align:center;width:112px;height:33px;margin:0px auto;'><a href='http://www.adobe.com/go/getflashplayer'><img src='http://www.adobe.com/images/shared/download_buttons/get_flash_player.gif' alt='Get Adobe Flash player' width='112' height='33'></img></a></div></div>")};inst.checkType=function(href){if(!href)return-1;if(href.match(/\.(jpg|gif|png|bmp|jpeg)(.*)?$/i))return 0;
if(href.match(/[^\.]\.(swf)\s*$/i))return 1;if(href.match(/\.(mp4|m4v|ogv|ogg|webm)(.*)?$/i))return 2;if(href.match(/\:\/\/.*(youtube\.com)/i)||href.match(/\:\/\/.*(youtu\.be)/i))return 3;if(href.match(/\:\/\/.*(vimeo\.com)/i))return 4;if(href.match(/[^\.]\.(pdf)\s*$/i))return 5;if(href.match(/[^\.]\.(mp3)\s*$/i))return 6;if(href.match(/[^\.]\.(flv)\s*$/i))return 8;return 7};inst.showLightbox=function(type,href,title,width,height,webm,ogg){inst.$next.hide();inst.$prev.hide();inst.reset();inst.$lightbox.show();
if(!inst.options.supportCSSPositionFixed)inst.$lightbox.css("top",$(window).scrollTop());var winH=window.innerHeight?window.innerHeight:$(window).height();var boxW=inst.options.loadingwidth+2*inst.options.bordersize;var boxH=inst.options.loadingheight+2*inst.options.bordersize;var boxT=Math.round(winH/2-boxH/2);if(inst.options.titlepos!="over")boxT-=Math.round(inst.options.barheight/2);inst.$lightboxBox.css({"margin-top":boxT,"width":boxW,"height":boxH});inst.$elemWrap.css({"width":boxW,"height":boxH});
inst.loadElem(new Array(type,href,title,null,width,height,webm,ogg))};inst.addItem=function(href,title,group,width,height,webm,ogg){type=inst.checkType(href);inst.elemArray.push(new Array(type,href,title,group,width,height,webm,ogg))};inst.showItem=function(href){if(inst.elemArray.length<=0)return true;inst.hideObjects();for(var i=0;i<inst.elemArray.length;i++)if(inst.elemArray[i][ELEM_HREF]==href)break;if(i==inst.elemArray.length)return true;inst.options.curElem=i;inst.options.nextElem=-1;inst.options.prevElem=
-1;inst.calcNextPrevElem();inst.$next.hide();inst.$prev.hide();inst.reset();inst.$lightbox.show();if(!inst.options.supportCSSPositionFixed)inst.$lightbox.css("top",$(window).scrollTop());var winH=window.innerHeight?window.innerHeight:$(window).height();var boxW=inst.options.loadingwidth+2*inst.options.bordersize;var boxH=inst.options.loadingheight+2*inst.options.bordersize;var boxT=Math.round(winH/2-boxH/2);if(inst.options.titlepos!="over")boxT-=Math.round(inst.options.barheight/2);inst.$lightboxBox.css({"margin-top":boxT,
"width":boxW,"height":boxH});inst.$elemWrap.css({"width":boxW,"height":boxH});inst.loadCurElem();return false};inst.init();return inst.unbind("click").click(inst.clickHandler)}})(jQuery);
function ASTimer(timeout,callback,updatecallback){var updateinterval=50;var updateTimerId=null;var runningTime=0;var paused=false;var started=false;this.pause=function(){if(started){paused=true;clearInterval(updateTimerId)}};this.resume=function(){if(started&&paused){paused=false;updateTimerId=setInterval(function(){runningTime+=updateinterval;if(runningTime>timeout){clearInterval(updateTimerId);if(callback)callback()}if(updatecallback)updatecallback(runningTime/timeout)},updateinterval)}};this.stop=
function(){clearInterval(updateTimerId);if(updatecallback)updatecallback(-1);runningTime=0;paused=false;started=false};this.start=function(){runningTime=0;paused=false;started=true;updateTimerId=setInterval(function(){runningTime+=updateinterval;if(runningTime>timeout){clearInterval(updateTimerId);if(callback)callback()}if(updatecallback)updatecallback(runningTime/timeout)},updateinterval)}}
var ASPlatforms={flashInstalled:function(){var flashInstalled=false;try{if(new ActiveXObject("ShockwaveFlash.ShockwaveFlash"))flashInstalled=true}catch(e){if(navigator.mimeTypes["application/x-shockwave-flash"])flashInstalled=true}return flashInstalled},html5VideoSupported:function(){return!!document.createElement("video").canPlayType},isChrome:function(){return navigator.userAgent.match(/Chrome/i)!=null},isFirefox:function(){return navigator.userAgent.match(/Firefox/i)!=null},isOpera:function(){return navigator.userAgent.match(/Opera/i)!=
null||navigator.userAgent.match(/OPR\//i)!=null},isSafari:function(){return navigator.userAgent.match(/Safari/i)!=null},isAndroid:function(){return navigator.userAgent.match(/Android/i)!=null},isIPad:function(){return navigator.userAgent.match(/iPad/i)!=null},isIPhone:function(){return navigator.userAgent.match(/iPod/i)!=null||navigator.userAgent.match(/iPhone/i)!=null},isIOS:function(){return this.isIPad()||this.isIPhone()},isIE9:function(){return navigator.userAgent.match(/MSIE/i)!=null&&this.html5VideoSupported()&&
!this.isOpera()},isIE8:function(){return navigator.userAgent.match(/MSIE 8/i)!=null&&!this.isOpera()},isIE7:function(){return navigator.userAgent.match(/MSIE 7/i)!=null&&!this.isOpera()},isIE6:function(){return navigator.userAgent.match(/MSIE 6/i)!=null&&!this.isOpera()},isIE678:function(){return this.isIE6()||this.isIE7()||this.isIE8()},isIE6789:function(){return this.isIE6()||this.isIE7()||this.isIE8()||this.isIE9()},css33dTransformSupported:function(){return!this.isIE6()&&!this.isIE7()&&!this.isIE8()&&
!this.isIE9()&&!this.isOpera()},applyBrowserStyles:function(object,applyToValue){var ret={};for(var key in object){ret[key]=object[key];ret["-webkit-"+key]=applyToValue?"-webkit-"+object[key]:object[key];ret["-moz-"+key]=applyToValue?"-moz-"+object[key]:object[key];ret["-ms-"+key]=applyToValue?"-ms-"+object[key]:object[key];ret["-o-"+key]=applyToValue?"-o-"+object[key]:object[key]}return ret}};
(function($){$.fn.amazingcarousel=function(options){var ELEM_ID=0,ELEM_SRC=1,ELEM_TITLE=2,ELEM_DESCRIPTION=3,ELEM_LINK=4,ELEM_TARGET=5,ELEM_VIDEO=6,ELEM_THUMBNAIL=7,ELEM_LIGHTBOX=8,ELEM_LIGHTBOXWIDTH=9,ELEM_LIGHTBOXHEIGHT=10;var TYPE_IMAGE=1,TYPE_SWF=2,TYPE_MP3=3,TYPE_PDF=4,TYPE_VIDEO_FLASH=5,TYPE_VIDEO_MP4=6,TYPE_VIDEO_OGG=7,TYPE_VIDEO_WEBM=8,TYPE_VIDEO_YOUTUBE=9,TYPE_VIDEO_VIMEO=10;var AmazingCarousel=function(container,options,id){this.container=container;this.options=options;this.id=id;this.transitionTimeout=
null;this.arrowTimeout=null;this.lightboxArray=[];this.visibleItems=this.options.visibleitems;this.itemSize=this.options.width;this.currentItem=0;this.elemLength=0;this.elemTotalCount=0;this.initData(this.init)};AmazingCarousel.prototype={initData:function(onSuccess){this.readTags();onSuccess(this)},readTags:function(){var items=$("li.amazingcarousel-item",this.container);this.elemLength=items.length;this.elemTotalCount=this.elemLength;var i;if(this.options.random){for(i=this.elemLength-1;i>0;i--){var index=
Math.floor(Math.random()*i);items.eq(index).insertBefore(items.eq(i));items.eq(i).insertBefore(items.eq(index))}items=$("li.amazingcarousel-item",this.container)}if(this.elemLength>1&&this.options.circular){var cloneCount=Math.min(this.options.visibleitems*2,this.elemLength);for(i=0;i<cloneCount;i++)$("ul.amazingcarousel-list",this.container).append(items.eq(i).clone(true));this.elemTotalCount+=cloneCount}$("ul.amazingcarousel-list",this.container).append("<div style='clear:both;'></div>")},init:function(instance){if(instance.elemLength<=
0)return;instance.isAnimating=false;instance.isPaused=!instance.options.autoplay;instance.tempPaused=false;instance.loopCount=0;instance.createPlayVideo();instance.createHoverOverlay();instance.createStyle();instance.createNav();instance.createArrows();instance.createBackgroundImage();instance.createItemBackgroundImage();instance.createBottomShadow();instance.createItemBottomShadow();instance.createWatermark();instance.createSliderTimeout();instance.createGoogleFonts();instance.enableSwipe();var $img=
$(".amazingcarousel-image",this.container).find("img");if($img.length)$img.eq(0).one("load",function(){instance.resizeCarousel()}).each(function(){if(this.complete)$(this).load()});else instance.resizeCarousel();if(instance.options.responsive)$(window).resize(function(){instance.resizeCarousel();instance.resizeNav()});$(window).load(function(){instance.resizeCarousel();instance.resizeNav()});instance.resizeNav();instance.container.trigger("amazingcarousel.switch",[-1,0]);if(!instance.isPaused&&!instance.tempPaused)instance.sliderTimeout.start()},
getParams:function(){var result={};var params=window.location.search.substring(1).split("&");for(var i=0;i<params.length;i++){var value=params[i].split("=");if(value&&value.length==2)result[value[0].toLowerCase()]=unescape(value[1])}return result},enableSwipe:function(){if(this.options.enabletouchswipe){var instance=this;$(".amazingcarousel-list-container",this.container).touchSwipe({preventWebBrowser:false,swipeLeft:function(){instance.slideRun(-1)},swipeRight:function(){instance.slideRun(-2)}})}},
createPlayVideo:function(){if(!this.options.showplayvideo)return;var instance=this;$(".amazingcarousel-image",this.container).each(function(){var $this=$(this);var isVideo=false;var isLightboxVideo=false;var videoUrl="";var videoWebmUrl="";$("img",$this).each(function(){if($(this).data("video")){videoUrl=$(this).data("video");if($(this).data("videowebm"))videoWebmUrl=$(this).data("videowebm");isVideo=true;return false}else if($(this).parent()[0].nodeName.toLowerCase()=="a")if($(this).parent().hasClass("html5lightbox")){var type=
instance.checkVideoType($(this).parent().attr("href"));if(type==TYPE_VIDEO_YOUTUBE||type==TYPE_VIDEO_VIMEO||type==TYPE_VIDEO_MP4||type==TYPE_VIDEO_WEBM)isLightboxVideo=true}});if(isVideo||isLightboxVideo){var pos="center center";switch(instance.options.playvideoimagepos){case "topleft":pos="left top";break;case "topright":pos="right top";break;case "bottomleft":pos="left bottom";break;case "bottomright":pos="right bottom";break}var $playVideo=$('<div class="amazingcarousel-play-video" style="position:absolute;left:0;top:0;width:100%;height:100%;cursor:pointer;'+
"background-image:url('"+instance.options.skinsfolder+instance.options.playvideoimage+"');background-repeat:no-repeat;"+"background-position:"+pos+';"></div>');$playVideo.appendTo($this);if(isVideo)$playVideo.click(function(){$this.find("img").css({visibility:"hidden"});instance.playVideo($(this),videoUrl,videoWebmUrl);$(this).unbind("click")})}})},playVideo:function($videoDiv,videoUrl,videoWebmUrl){if(videoUrl.length<=0)return;this.sliderTimeout.stop();this.tempPaused=true;var type=this.checkVideoType(videoUrl);
if(type==TYPE_VIDEO_YOUTUBE)this.playYoutubeVideo(videoUrl,$videoDiv);else if(type==TYPE_VIDEO_VIMEO)this.playVimeoVideo(videoUrl,$videoDiv);else if(type==TYPE_VIDEO_MP4)this.playMp4Video(videoUrl,videoWebmUrl,true,$videoDiv)},playMp4Video:function(href,webmhref,autoplay,$videoWrapper){var isHTML5=true;if(ASPlatforms.isIE6789())isHTML5=false;else if((ASPlatforms.isFirefox()||ASPlatforms.isOpera())&&!webmhref)isHTML5=false;if(isHTML5){var videoSrc=ASPlatforms.isFirefox()||ASPlatforms.isOpera()?webmhref:
href;this.embedHTML5Video($videoWrapper,videoSrc,autoplay)}else{var videoFile=href;if(videoFile.charAt(0)!="/"&&videoFile.substring(0,5)!="http:"&&videoFile.substring(0,6)!="https:")videoFile=this.options.htmlfolder+videoFile;this.embedFlash($videoWrapper,"100%","100%",this.options.jsfolder+"html5boxplayer.swf","transparent",{width:"100%",height:"100%",videofile:videoFile,hdfile:"",ishd:"0",autoplay:autoplay?"1":"0",errorcss:".amazingcarousel-error"+this.options.errorcss,id:this.id})}},embedHTML5Video:function($container,
src,autoPlay){$container.html("<div class='amazingcarousel-video-container-"+this.id+"' style='position:relative;display:block;width:100%;height:100%;'><video style='width:100%;height:100%;' controls ></div>");$("video",$container).get(0).setAttribute("src",src);if(autoPlay)$("video",$container).get(0).play()},embedFlash:function($container,w,h,src,wmode,flashVars){if(ASPlatforms.flashInstalled()){var htmlOptions={pluginspage:"http://www.adobe.com/go/getflashplayer",quality:"high",allowFullScreen:"true",
allowScriptAccess:"always",type:"application/x-shockwave-flash"};htmlOptions.width=w;htmlOptions.height=h;htmlOptions.src=src;htmlOptions.wmode=wmode;htmlOptions.flashVars=$.param(flashVars);var htmlString="";for(var key in htmlOptions)htmlString+=key+"="+htmlOptions[key]+" ";$container.html("<embed "+htmlString+"/>")}else $container.html("<div class='amazingcarousel-video-error' style='display:block;position:absolute;text-align:center;width:100%;height:100%;left:0px;top:0px;'><div>The required Adobe Flash Player plugin is not installed</div><br /><div style='display:block;position:relative;text-align:center;width:112px;height:33px;margin:0px auto;'><a href='http://www.adobe.com/go/getflashplayer'><img src='http://www.adobe.com/images/shared/download_buttons/get_flash_player.gif' alt='Get Adobe Flash player' width='112' height='33'></img></a></div>")},
playYoutubeVideo:function(href,$videoWrapper){if(this.options.previewmode){$videoWrapper.html("<div class='amazingcarousel-video-error' style='display:block;position:absolute;left:0;top:0;width:100%;height:100%;color:#fff;background-color:#333;'>To view YouTube video, publish the carousel then open it in your web browser</div>");return}else{var src=href+(href.indexOf("?")<0?"?":"&")+"autoplay=1&wmode=transparent&rel=0&autohide=1";$videoWrapper.html("<iframe width='100%' height='100%' src='"+src+"' frameborder='0' webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>")}},
playVimeoVideo:function(href,$videoWrapper){if(this.options.previewmode){$videoWrapper.html("<div class='amazingcarousel-video-error' style='display:block;position:absolute;left:0;top:0;width:100%;height:100%;color:#fff;background-color:#333;'>To view Vimeo video, publish the carousel then open it in your web browser</div>");return}else{var src=href+(href.indexOf("?")<0?"?":"&")+"autoplay=1&api=1";$videoWrapper.html("<iframe width='100%' height='100%' src='"+src+"' frameborder='0' webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>")}},
checkVideoType:function(href){if(!href)return-1;if(href.match(/\.(flv)(.*)?$/i))return TYPE_VIDEO_FLASH;if(href.match(/\.(mp4|m4v)(.*)?$/i))return TYPE_VIDEO_MP4;if(href.match(/\.(ogv|ogg)(.*)?$/i))return TYPE_VIDEO_OGG;if(href.match(/\.(webm)(.*)?$/i))return TYPE_VIDEO_WEBM;if(href.match(/\:\/\/.*(youtube\.com)/i)||href.match(/\:\/\/.*(youtu\.be)/i))return TYPE_VIDEO_YOUTUBE;if(href.match(/\:\/\/.*(vimeo\.com)/i))return TYPE_VIDEO_VIMEO;return 0},createHoverOverlay:function(){if(!this.options.showhoveroverlay)return;
var instance=this;$(".amazingcarousel-image",this.container).each(function(){var $this=$(this);var isLightbox=false;$("img",$this).each(function(){if($(this).parent()[0].nodeName.toLowerCase()=="a")if($(this).parent().hasClass("html5lightbox")){isLightbox=true;return false}});if(isLightbox){var $hoverImage=$('<div class="amazingcarousel-hover-effect" style="display:none;position:absolute;left:0;top:0;width:100%;height:100%;cursor:pointer;'+"background-image:url('"+instance.options.skinsfolder+instance.options.hoveroverlayimage+
"');background-repeat:no-repeat;"+'background-position:center center;"></div>');$hoverImage.appendTo($this);var $img=$("img",$this);$hoverImage.click(function(){$img.click()});$(this).hover(function(){if(ASPlatforms.isIE678())$hoverImage.show();else $hoverImage.fadeIn()},function(){if(ASPlatforms.isIE678())$hoverImage.hide();else $hoverImage.fadeOut()})}})},createStyle:function(){$("ul.amazingcarousel-list",this.container).css({display:"block",position:"relative","list-style-type":"none","list-style-image":"none",
"background-image":"none","background-color":"transparent",padding:0,margin:0});$("li.amazingcarousel-item",this.container).css({display:"block",position:"relative","background-image":"none","background-color":"transparent",margin:0,padding:0,"float":this.options.direction=="horizontal"?"left":"top"});var m=0;if(this.options.spacing>0)if(this.options.direction=="horizontal"){var s=Math.min(this.options.spacing/2);m="0 "+s+"px"}else m="0 0 "+this.options.spacing+"px 0";var itemCss={};itemCss["position"]=
"relative";itemCss["margin"]=m;$("div.amazingcarousel-item-container",this.container).css(itemCss);var listCss={};listCss["position"]="relative";$("div.amazingcarousel-list-container",this.container).css(listCss)},hideVideo:function(start){var instance=this;var index=0;$("li.amazingcarousel-item",this.container).each(function(){if(index<start||index>=start+instance.visibleItems)$(".amazingcarousel-play-video",$(this)).empty();index++})},resizeCarousel:function(){this.visibleItems=this.options.visibleitems;
this.itemSize=this.options.width;if(this.options.direction=="horizontal"&&this.options.responsive){var screenWidth=$(window).width();for(var i in this.options.screenquery)if(screenWidth<this.options.screenquery[i].screenwidth)this.visibleItems=this.options.screenquery[i].visibleitems;var conWidth=$(".amazingcarousel-list-container",this.container).width();this.itemSize=Math.round(conWidth/this.visibleItems)}$("li.amazingcarousel-item",this.container).css({width:this.itemSize+"px"});if(this.options.direction==
"vertical")this.itemSize=$("li.amazingcarousel-item",this.container).height();var sizeProp=this.options.direction=="horizontal"?"width":"height";$("ul.amazingcarousel-list",this.container).css(sizeProp,this.itemSize*(this.options.circular?this.elemTotalCount:this.elemLength)+"px");var cssProp=this.options.direction=="horizontal"?"margin-left":"margin-top";var itemSize=this.options.direction=="horizontal"?this.itemSize:this.itemHeight;var pos=-itemSize*this.currentItem;$("ul.amazingcarousel-list",
this.container).css(cssProp,pos+"px");if(this.options.direction=="vertical")$("div.amazingcarousel-list-container",this.container).css({height:String(this.itemSize*this.visibleItems+this.options.spacing*(this.visibleItems-1))+"px"});this.hideVideo(this.currentItem);this.hideArrows()},createGoogleFonts:function(){if(this.options.previewmode)return;if(this.options.addgooglefonts&&this.options.googlefonts&&this.options.googlefonts.length>0){var fontRef=("https:"==document.location.protocol?"https":"http")+
"://fonts.googleapis.com/css?family="+this.options.googlefonts;var fontLink=document.createElement("link");fontLink.setAttribute("rel","stylesheet");fontLink.setAttribute("type","text/css");fontLink.setAttribute("href",fontRef);document.getElementsByTagName("head")[0].appendChild(fontLink)}},createWatermark:function(){if(!this.options.showwatermark)return;if(this.options.watermarkstyle=="text"&&this.options.watermarktext.length<=0)return;if(this.options.watermarkstyle=="image"&&this.options.watermarkimage.length<=
0)return;var wmCode="<div style='"+this.options.watermarkpositioncss;if(this.options.watermarkstyle=="text")wmCode+=this.options.watermarktextcss;if(this.options.watermarklink)wmCode+="cursor:pointer;";wmCode+="'>";if(this.options.watermarklink){wmCode+="<a href='"+this.options.watermarklink+"' style='"+this.options.watermarklinkcss+"'";if(this.options.watermarktarget)wmCode+=" target='"+this.options.watermarktarget+"'";wmCode+=">"}if(this.options.watermarkstyle=="text")wmCode+=this.options.watermarktext;
else if(this.options.watermarkstyle=="image")wmCode+="<img src='"+this.options.skinsfolder+this.options.watermarkimage+"' style='border:none;' />";if(this.options.watermarklink)wmCode+="</a>";wmCode+="</div>";$(".amazingcarousel-image",this.container).eq(0).append($(wmCode));if(this.elemLength<this.elemTotalCount)$(".amazingcarousel-image",this.container).eq(this.elemLength).append($(wmCode))},createSliderTimeout:function(){var instance=this;this.sliderTimeout=new ASTimer(this.options.interval,function(){instance.slideRun(-1)},
null);if(instance.options.pauseonmouseover)this.container.hover(function(){if(!instance.isPaused)instance.sliderTimeout.pause()},function(){if(!instance.isPaused)instance.sliderTimeout.resume()})},createItemBottomShadow:function(){if(!this.options.showitembottomshadow)return;var l=(100-this.options.itembottomshadowimagewidth)/2;var shadow="<div class='amazingcarousel-item-bottom-shadow' "+"style='display:block;position:absolute;left:"+l+"%;top:"+this.options.itembottomshadowimagetop+"%;"+"width:"+
this.options.itembottomshadowimagewidth+"%;height:auto;'>"+"<img src='"+this.options.skinsfolder+this.options.itembottomshadowimage+"' style='display:block;position:relative;width:678px;height:43px;"+"border:0;box-shadow:none;-moz-box-shadow:none;-webkit-box-shadow:none;border-radius:0;-moz-border-radius:0;-webkit-border-radius:0;"+"' />"+"</div>";$("li.amazingcarousel-item",this.container).prepend(shadow)},createBottomShadow:function(){if(!this.options.showbottomshadow)return;var l=(100-this.options.bottomshadowimagewidth)/
2;var shadow="<div class='amazingcarousel-bottom-shadow' "+"style='display:block;position:absolute;left:"+l+"%;top:"+this.options.bottomshadowimagetop+"%;"+"width:"+this.options.bottomshadowimagewidth+"%;height:auto;'>"+"<img src='"+this.options.skinsfolder+this.options.bottomshadowimage+"' style='display:block;position:relative;width:100%;height:auto;"+"border:0;box-shadow:none;-moz-box-shadow:none;-webkit-box-shadow:none;border-radius:0;-moz-border-radius:0;-webkit-border-radius:0;"+"' />"+"</div>";
this.container.prepend(shadow)},createItemBackgroundImage:function(){if(!this.options.showitembackgroundimage||!this.options.itembackgroundimage)return;var l=(100-this.options.itembackgroundimagewidth)/2;var background="<div class='amazingcarousel-background-image' "+"style='display:block;position:absolute;left:"+l+"%;top:"+this.options.itembackgroundimagetop+"%;width:"+this.options.itembackgroundimagewidth+"%;height:auto;'>"+"<img src='"+this.options.skinsfolder+this.options.itembackgroundimage+
"' style='display:block;position:relative;width:100%;height:auto;"+"border:0;box-shadow:none;-moz-box-shadow:none;-webkit-box-shadow:none;border-radius:0;-moz-border-radius:0;-webkit-border-radius:0;"+"' />"+"</div>";$("li.amazingcarousel-item",this.container).prepend(background)},createBackgroundImage:function(){if(!this.options.showbackgroundimage||!this.options.backgroundimage)return;var l=(100-this.options.backgroundimagewidth)/2;var background="<div class='amazingcarousel-background-image' "+
"style='display:block;position:absolute;left:"+l+"%;top:"+this.options.backgroundimagetop+"%;width:"+this.options.backgroundimagewidth+"%;height:auto;'>"+"<img src='"+this.options.skinsfolder+this.options.backgroundimage+"' style='display:block;position:relative;width:100%;height:auto;"+"border:0;box-shadow:none;-moz-box-shadow:none;-webkit-box-shadow:none;border-radius:0;-moz-border-radius:0;-webkit-border-radius:0;"+"' />"+"</div>";this.container.prepend(background)},createArrows:function(){if(this.options.arrowstyle==
"none")return;var instance=this;var $prevArrow=$(".amazingcarousel-prev",this.container);var $nextArrow=$(".amazingcarousel-next",this.container);$prevArrow.css({overflow:"hidden",position:"absolute",cursor:"pointer",width:this.options.arrowwidth+"px",height:this.options.arrowheight+"px",background:"url('"+this.options.skinsfolder+this.options.arrowimage+"') no-repeat left top"});if(ASPlatforms.isIE678())$prevArrow.css({opacity:"inherit",filter:"inherit"});$nextArrow.css({overflow:"hidden",position:"absolute",
cursor:"pointer",width:this.options.arrowwidth+"px",height:this.options.arrowheight+"px",background:"url('"+this.options.skinsfolder+this.options.arrowimage+"') no-repeat right top"});if(ASPlatforms.isIE678())$nextArrow.css({opacity:"inherit",filter:"inherit"});$prevArrow.hover(function(){$(this).css({"background-position":"left bottom"})},function(){$(this).css({"background-position":"left top"})});$nextArrow.hover(function(){$(this).css({"background-position":"right bottom"})},function(){$(this).css({"background-position":"right top"})});
if(this.options.arrowstyle=="always"){$prevArrow.css({display:"block"});$nextArrow.css({display:"block"})}else{$prevArrow.css({display:"none"});$nextArrow.css({display:"none"});this.container.hover(function(){clearTimeout(instance.arrowTimeout);if(instance.options.circular||instance.currentItem>0)if(ASPlatforms.isIE678())$prevArrow.show();else $prevArrow.fadeIn();if(instance.options.circular||instance.currentItem<instance.elemLength-instance.visibleItems)if(ASPlatforms.isIE678())$nextArrow.show();
else $nextArrow.fadeIn()},function(){instance.arrowTimeout=setTimeout(function(){if(ASPlatforms.isIE678()){$prevArrow.hide();$nextArrow.hide()}else{$prevArrow.fadeOut();$nextArrow.fadeOut()}},instance.options.arrowhideonmouseleave)})}$prevArrow.click(function(){instance.slideRun(-2)});$nextArrow.click(function(){instance.slideRun(-1)})},hideArrows:function(){var $prevArrow=$(".amazingcarousel-prev",this.container);var $nextArrow=$(".amazingcarousel-next",this.container);if(!this.options.circular&&
this.currentItem<=0)$prevArrow.hide();else if(this.options.arrowstyle=="always")$prevArrow.show();if(!this.options.circular&&this.currentItem>=this.elemLength-this.visibleItems)$nextArrow.hide();else if(this.options.arrowstyle=="always")$nextArrow.show()},createNav:function(){if(this.options.navstyle=="none")return;var $nav=$(".amazingcarousel-nav",this.container);var $bulletWrapper=$("<div class='amazingcarousel-bullet-wrapper'></div>");$bulletWrapper.appendTo($nav);var $bulletList=$("<div class='amazingcarousel-bullet-list'></div>");
$bulletList.appendTo($bulletWrapper);var bulletSize=this.options.navdirection=="vertical"?this.options.navwidth:this.options.navheight;var len=this.elemLength*bulletSize+(this.elemLength-1)*this.options.navspacing;if(this.options.navdirection=="vertical"){$bulletWrapper.css({height:len+"px",width:"auto"});$bulletList.css({height:len+"px",width:"auto"})}else{$bulletWrapper.css({width:len+"px",height:"auto"});$bulletList.css({width:len+"px",height:"auto"})}var $bullet;for(var i=0;i<this.elemLength;i++){$bullet=
this.createNavBullet(i);$bulletList.append($bullet)}var instance=this;this.container.bind("amazingcarousel.switch",function(event,prev,cur){for(var i=0;i<instance.elemLength;i++)$(".amazingcarousel-bullet-"+i,instance.container)["bulletNormal"+instance.id]();if(cur>=0){if(instance.options.navmode=="page")cur=Math.floor(cur/instance.visibleItems);$(".amazingcarousel-bullet-"+cur,instance.container)["bulletSelected"+instance.id]()}})},createNavBullet:function(index){var f=this.options.navdirection==
"vertical"?"top":"left";var marginF=this.options.navdirection=="vertical"?"bottom":"right";var spacing=index==this.elemLength-1?0:this.options.navspacing;var w=this.options.navwidth;var h=this.options.navheight;var $bullet=$("<div class='amazingcarousel-bullet-"+index+"' style='position:relative;float:"+f+";margin-"+marginF+":"+spacing+"px;width:"+w+"px;height:"+h+"px;cursor:pointer;'></div>");$bullet.data("index",index);var instance=this;$bullet.hover(function(){var bulletIndex=$(this).data("index");
if(bulletIndex!=instance.currentItem)$(this)["bulletHighlight"+instance.id]();if(instance.options.navswitchonmouseover){if(instance.options.navmode=="page")bulletIndex=instance.visibleItems*bulletIndex;instance.slideRun(bulletIndex)}},function(){var cur=instance.currentItem;if(instance.options.navmode=="page")cur=Math.floor(cur/instance.visibleItems);if($(this).data("index")!=cur)$(this)["bulletNormal"+instance.id]()});$bullet.click(function(){var bulletIndex=$(this).data("index");if(instance.options.navmode==
"page")bulletIndex=instance.visibleItems*bulletIndex;instance.slideRun(bulletIndex)});$bullet.css({background:"url('"+this.options.skinsfolder+this.options.navimage+"') no-repeat left top"});$.fn["bulletNormal"+this.id]=function(){$(this).css({"background-position":"left top"})};$.fn["bulletHighlight"+this.id]=$.fn["bulletSelected"+this.id]=function(){$(this).css({"background-position":"left bottom"})};return $bullet},resizeNav:function(){if(this.options.navstyle=="none"||this.options.navmode=="item")return;
var page=Math.ceil(this.elemLength/this.visibleItems);var i;for(i=0;i<page;i++)$(".amazingcarousel-bullet-"+i,this.container).css({display:"block"});for(i=page;i<this.elemLength;i++)$(".amazingcarousel-bullet-"+i,this.container).css({display:"none"});var curPage=Math.floor(this.currentItem/this.visibleItems);for(i=0;i<this.elemLength;i++)$(".amazingcarousel-bullet-"+i,this.container)["bulletNormal"+this.id];$(".amazingcarousel-bullet-"+curPage,this.container)["bulletHighlight"+this.id];var bulletSize=
this.options.navdirection=="vertical"?this.options.navwidth:this.options.navheight;var len=page*bulletSize+(page-1)*this.options.navspacing;if(this.options.navdirection=="vertical")$(".amazingcarousel-bullet-wrapper",this.container).css({height:len+"px",width:"auto"});else $(".amazingcarousel-bullet-wrapper",this.container).css({width:len+"px",height:"auto"})},slideRun:function(index){if(this.isAnimating)return;if(index==this.currentItem||index<-2||index>=this.elemLength)return;var scrollItems;if(index>=
0)scrollItems=1;else{scrollItems=this.visibleItems;if(this.options.scrollmode=="item")if(scrollItems>this.options.scrollitems)scrollItems=this.options.scrollitems}var nextItem,dir;if(index==-2){dir=-1;nextItem=this.currentItem-scrollItems}else if(index==-1){dir=1;nextItem=this.currentItem+scrollItems}else{dir=index>this.currentItem?1:-1;nextItem=index}if(dir<0){if(nextItem<0)nextItem=this.options.circular?this.elemLength+nextItem:0}else if(this.options.circular){if(nextItem>=this.elemLength)nextItem=
nextItem-this.elemLength}else if(nextItem>this.elemLength-this.visibleItems)nextItem=this.elemLength-this.visibleItems;if(nextItem==this.currentItem)return;this.isAnimating=true;this.sliderTimeout.stop();this.tempPaused=false;var animCss=this.options.direction=="horizontal"?"margin-left":"margin-top";var animItemSize=this.itemSize;if(this.options.direction=="vertical")animItemSize+=this.options.spacing;var animInitPos=animItemSize*this.currentItem;var animTargetPos=animItemSize*nextItem;var showStart=
nextItem;if(this.options.circular)if(dir<0){if(nextItem>this.currentItem)animInitPos=animItemSize*(this.elemLength+this.currentItem)}else if(nextItem>this.elemLength-scrollItems&&this.elemLength<2*scrollItems)animInitPos=animItemSize*(nextItem-scrollItems);else if(nextItem<this.currentItem){animTargetPos=animItemSize*(this.elemLength+nextItem);showStart=this.elemLength+nextItem}animInitPos=-animInitPos;animTargetPos=-animTargetPos;$("ul.amazingcarousel-list",this.container).css(animCss,animInitPos+
"px");var animProp={};animProp[animCss]=animTargetPos+"px";this.container.trigger("amazingcarousel.switch",[this.currentItem,nextItem]);var prevItem=this.currentItem;this.currentItem=nextItem;this.container.trigger("amazingcarousel.switch",[prevItem,nextItem]);this.hideVideo(showStart);this.hideArrows();var instance=this;$("ul.amazingcarousel-list",this.container).animate(animProp,this.options.transitionduration,this.options.transitioneasing,function(){instance.isAnimating=false;if(instance.options.loop>
0)if(instance.currentItem+instance.visibleItems>=instance.elemLength){instance.loopCount++;if(instance.options.loop<=instance.loopCount)instance.isPaused=true}if(!instance.isPaused&&!instance.tempPaused)instance.sliderTimeout.start()})}};options=options||{};for(var key in options)if(key.toLowerCase()!==key){options[key.toLowerCase()]=options[key];delete options[key]}this.each(function(){this.options=$.extend({},options);var instance=this;$.each($(this).data(),function(key,value){instance.options[key.toLowerCase()]=
value});var searchoptions={};var searchstring=window.location.search.substring(1).split("&");for(var i=0;i<searchstring.length;i++){var keyvalue=searchstring[i].split("=");if(keyvalue&&keyvalue.length==2){var key=keyvalue[0].toLowerCase();var value=unescape(keyvalue[1]).toLowerCase();if(value=="true")searchoptions[key]=true;else if(value=="false")searchoptions[key]=false;else searchoptions[key]=value}}this.options=$.extend(this.options,searchoptions);var defaultOptions={previewmode:false,direction:"horizontal",
autoplay:false,pauseonmouseover:true,interval:3E3,loop:0,random:true,circular:true,scrollmode:"page",scrollitems:1,skinsfoldername:"skins",showplayvideo:false,playvideoimage:"playvideo-64-64-0.png",playvideoimagepos:"center",showhoveroverlay:true,hoveroverlayimage:"hoveroverlay-64-64-0.png",enabletouchswipe:true,responsive:false,spacing:24,showbackgroundimage:false,backgroundimage:"background.png",backgroundimagewidth:110,backgroundimagetop:-40,showitembackgroundimage:false,itembackgroundimage:"background.png",
itembackgroundimagewidth:150,itembackgroundimagetop:0,showbottomshadow:false,bottomshadowimage:"bottomshadow.png",bottomshadowimagewidth:110,bottomshadowimagetop:95,showitembottomshadow:false,itembottomshadowimage:"bottomshadow.png",itembottomshadowimagewidth:110,itembottomshadowimagetop:100,arrowstyle:"always",arrowimage:"arrows.png",arrowwidth:48,arrowheight:48,arrowhideonmouseleave:1E3,navdirection:"horizontal",navstyle:"bullets",navmode:"page",navswitchonmouseover:false,navwidth:16,navheight:16,
navspacing:8,navimage:"bullet.png",transitionduration:1E3,transitioneasing:"easeOutQuad",versionmark:"AMCom",showwatermarkdefault:true,watermarkstyledefault:"text",watermarktextdefault:"amazingcarousel.com",watermarkimagedefault:"",watermarklinkdefault:"http://amazingcarousel.com?source=watermark",watermarktargetdefault:"_blank",watermarkpositioncssdefault:"display:block;position:absolute;bottom:8px;right:8px;",watermarktextcssdefault:"font:12px Arial,Tahoma,Helvetica,sans-serif;color:#666;padding:2px 4px;-webkit-border-radius:2px;-moz-border-radius:2px;border-radius:2px;background-color:#fff;opacity:0.9;filter:alpha(opacity=90);",
watermarklinkcssdefault:"text-decoration:none;font:12px Arial,Tahoma,Helvetica,sans-serif;color:#333;"};this.options=$.extend(defaultOptions,this.options);if(this.options.versionmark!="AMC"+"om"){this.options.showwatermark=window.location.href.indexOf("://"+"amazin"+"gcarouse"+"l.com")>=0?false:this.options.showwatermarkdefault;this.options.watermarkstyle=this.options.watermarkstyledefault;this.options.watermarktext=this.options.watermarktextdefault;this.options.watermarkimage=this.options.watermarkimagedefault;
this.options.watermarklink=this.options.watermarklinkdefault;this.options.watermarktarget=this.options.watermarktargetdefault;this.options.watermarkpositioncss=this.options.watermarkpositioncssdefault;this.options.watermarktextcss=this.options.watermarktextcssdefault;this.options.watermarklinkcss=this.options.watermarklinkcssdefault}if(typeof amazingcarousel_previewmode!="undefined")this.options.previewmode=amazingcarousel_previewmode;this.options.htmlfolder=window.location.href.substr(0,window.location.href.lastIndexOf("/")+
1);if(this.options.skinsfoldername.length>0)this.options.skinsfolder=this.options.jsfolder+this.options.skinsfoldername+"/";else this.options.skinsfolder=this.options.jsfolder;new AmazingCarousel($(this),this.options,amazingcarouselId++)})}})(jQuery);
(function($){$.fn.touchSwipe=function(options){var defaults={preventWebBrowser:false,swipeLeft:null,swipeRight:null,swipeTop:null,swipeBottom:null};if(options)$.extend(defaults,options);return this.each(function(){var startX=-1,startY=-1;var curX=-1,curY=-1;function touchStart(event){var e=event.originalEvent;if(e.targetTouches.length>=1){startX=e.targetTouches[0].pageX;startY=e.targetTouches[0].pageY}else touchCancel(event)}function touchMove(event){if(defaults.preventWebBrowser)event.preventDefault();
var e=event.originalEvent;if(e.targetTouches.length>=1){curX=e.targetTouches[0].pageX;curY=e.targetTouches[0].pageY}else touchCancel(event)}function touchEnd(event){if(curX>0||curY>0){triggerHandler();touchCancel(event)}else touchCancel(event)}function touchCancel(event){startX=-1;startY=-1;curX=-1;curY=-1}function triggerHandler(){if(curX>startX){if(defaults.swipeRight)defaults.swipeRight.call()}else if(defaults.swipeLeft)defaults.swipeLeft.call();if(curY>startY){if(defaults.swipeBottom)defaults.swipeBottom.call()}else if(defaults.swipeTop)defaults.swipeTop.call()}
try{$(this).bind("touchstart",touchStart);$(this).bind("touchmove",touchMove);$(this).bind("touchend",touchEnd);$(this).bind("touchcancel",touchCancel)}catch(e){}})}})(jQuery);jQuery.easing["jswing"]=jQuery.easing["swing"];
jQuery.extend(jQuery.easing,{def:"easeOutQuad",swing:function(x,t,b,c,d){return jQuery.easing[jQuery.easing.def](x,t,b,c,d)},easeInQuad:function(x,t,b,c,d){return c*(t/=d)*t+b},easeOutQuad:function(x,t,b,c,d){return-c*(t/=d)*(t-2)+b},easeInOutQuad:function(x,t,b,c,d){if((t/=d/2)<1)return c/2*t*t+b;return-c/2*(--t*(t-2)-1)+b},easeInCubic:function(x,t,b,c,d){return c*(t/=d)*t*t+b},easeOutCubic:function(x,t,b,c,d){return c*((t=t/d-1)*t*t+1)+b},easeInOutCubic:function(x,t,b,c,d){if((t/=d/2)<1)return c/
2*t*t*t+b;return c/2*((t-=2)*t*t+2)+b},easeInQuart:function(x,t,b,c,d){return c*(t/=d)*t*t*t+b},easeOutQuart:function(x,t,b,c,d){return-c*((t=t/d-1)*t*t*t-1)+b},easeInOutQuart:function(x,t,b,c,d){if((t/=d/2)<1)return c/2*t*t*t*t+b;return-c/2*((t-=2)*t*t*t-2)+b},easeInQuint:function(x,t,b,c,d){return c*(t/=d)*t*t*t*t+b},easeOutQuint:function(x,t,b,c,d){return c*((t=t/d-1)*t*t*t*t+1)+b},easeInOutQuint:function(x,t,b,c,d){if((t/=d/2)<1)return c/2*t*t*t*t*t+b;return c/2*((t-=2)*t*t*t*t+2)+b},easeInSine:function(x,
t,b,c,d){return-c*Math.cos(t/d*(Math.PI/2))+c+b},easeOutSine:function(x,t,b,c,d){return c*Math.sin(t/d*(Math.PI/2))+b},easeInOutSine:function(x,t,b,c,d){return-c/2*(Math.cos(Math.PI*t/d)-1)+b},easeInExpo:function(x,t,b,c,d){return t==0?b:c*Math.pow(2,10*(t/d-1))+b},easeOutExpo:function(x,t,b,c,d){return t==d?b+c:c*(-Math.pow(2,-10*t/d)+1)+b},easeInOutExpo:function(x,t,b,c,d){if(t==0)return b;if(t==d)return b+c;if((t/=d/2)<1)return c/2*Math.pow(2,10*(t-1))+b;return c/2*(-Math.pow(2,-10*--t)+2)+b},
easeInCirc:function(x,t,b,c,d){return-c*(Math.sqrt(1-(t/=d)*t)-1)+b},easeOutCirc:function(x,t,b,c,d){return c*Math.sqrt(1-(t=t/d-1)*t)+b},easeInOutCirc:function(x,t,b,c,d){if((t/=d/2)<1)return-c/2*(Math.sqrt(1-t*t)-1)+b;return c/2*(Math.sqrt(1-(t-=2)*t)+1)+b},easeInElastic:function(x,t,b,c,d){var s=1.70158;var p=0;var a=c;if(t==0)return b;if((t/=d)==1)return b+c;if(!p)p=d*0.3;if(a<Math.abs(c)){a=c;var s=p/4}else var s=p/(2*Math.PI)*Math.asin(c/a);return-(a*Math.pow(2,10*(t-=1))*Math.sin((t*d-s)*2*
Math.PI/p))+b},easeOutElastic:function(x,t,b,c,d){var s=1.70158;var p=0;var a=c;if(t==0)return b;if((t/=d)==1)return b+c;if(!p)p=d*0.3;if(a<Math.abs(c)){a=c;var s=p/4}else var s=p/(2*Math.PI)*Math.asin(c/a);return a*Math.pow(2,-10*t)*Math.sin((t*d-s)*2*Math.PI/p)+c+b},easeInOutElastic:function(x,t,b,c,d){var s=1.70158;var p=0;var a=c;if(t==0)return b;if((t/=d/2)==2)return b+c;if(!p)p=d*0.3*1.5;if(a<Math.abs(c)){a=c;var s=p/4}else var s=p/(2*Math.PI)*Math.asin(c/a);if(t<1)return-0.5*a*Math.pow(2,10*
(t-=1))*Math.sin((t*d-s)*2*Math.PI/p)+b;return a*Math.pow(2,-10*(t-=1))*Math.sin((t*d-s)*2*Math.PI/p)*0.5+c+b},easeInBack:function(x,t,b,c,d,s){if(s==undefined)s=1.70158;return c*(t/=d)*t*((s+1)*t-s)+b},easeOutBack:function(x,t,b,c,d,s){if(s==undefined)s=1.70158;return c*((t=t/d-1)*t*((s+1)*t+s)+1)+b},easeInOutBack:function(x,t,b,c,d,s){if(s==undefined)s=1.70158;if((t/=d/2)<1)return c/2*t*t*(((s*=1.525)+1)*t-s)+b;return c/2*((t-=2)*t*(((s*=1.525)+1)*t+s)+2)+b},easeInBounce:function(x,t,b,c,d){return c-
jQuery.easing.easeOutBounce(x,d-t,0,c,d)+b},easeOutBounce:function(x,t,b,c,d){if((t/=d)<1/2.75)return c*7.5625*t*t+b;else if(t<2/2.75)return c*(7.5625*(t-=1.5/2.75)*t+0.75)+b;else if(t<2.5/2.75)return c*(7.5625*(t-=2.25/2.75)*t+0.9375)+b;else return c*(7.5625*(t-=2.625/2.75)*t+0.984375)+b},easeInOutBounce:function(x,t,b,c,d){if(t<d/2)return jQuery.easing.easeInBounce(x,t*2,0,c,d)*0.5+b;return jQuery.easing.easeOutBounce(x,t*2-d,0,c,d)*0.5+c*0.5+b}});
if(typeof ASYouTubeIframeAPIReady==="undefined"){var ASYouTubeIframeAPIReady=false;var ASYouTubeTimeout=0;function onYouTubeIframeAPIReady(){ASYouTubeIframeAPIReady=true}}if(typeof amazingcarouselId==="undefined")var amazingcarouselId=0;
